# Generated by Django 2.2.11 on 2020-03-19 19:40
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []
    operations = [
        CreateExtension('postgis'),
    ]
