# Generated by Django 2.2.11 on 2020-03-19 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geospatial point')),
                ('production_capacity', models.IntegerField(default=1, verbose_name='Capacidad de producción')),
                ('logistics_need', models.BooleanField(default=False, verbose_name='Necesidad logística')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Región')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
