# Generated by Django 2.2.11 on 2020-03-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_auto_20200320_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.IntegerField(choices=[(0, 'Esperando'), (1, 'Enviado'), (2, 'Recibido'), (3, 'Programado')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='logistica.Producer', verbose_name='Punto de producción'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Esperando'), (1, 'Enviado'), (2, 'Recibido'), (3, 'Programado')], default=0, verbose_name='Estado'),
        ),
    ]
