# Generated by Django 2.2.11 on 2020-03-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_auto_20200320_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='logistica.Resource', verbose_name='Recurso'),
        ),
    ]
